name: cable

environment:
  sdk: ">=2.1.0 <3.0.0"

description: >
  An extensible and simple logging framework.
version: 0.1.0+1
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/cable

dependencies:
  meta: ^1.1.0

dev_dependencies:
  test: ^0.12.0
